### ISSUE TITLE
Loading dataset - Google cloud server

### ISSUE THREAD

**Issue by kaplinserm** [klarman-cell-observatory/cirrocumulus#12]
Hello,

I use cirrocumulus on the google cloud platform.
I can load my website and import a dataset. 
When i click on open and then click on the dataset, I can view the dataset.
When I reload the page, click on open and then click on the dataset, I can only see an infinite loading page : why ?

Best regards

**Comment by joshua-gould** [comment]
Are you using Google App Engine? Do you see any error messages in your JavaScript console? Thanks.

**Comment by kaplinserm** [comment]
Yes and I don't see any errors.
My data are stored in the Google Cloud Platform Storage with permissions set to public access.

**Comment by joshua-gould** [comment]
Do you see any server side errors (see Error Reporting in Google console)? Can you please ensure you have the latest version of cirrocumulus (1.1.10.post2) installed?

**Comment by kaplinserm** [comment]
I see no error and I installed the last version of cirrocumulus.

**Comment by joshua-gould** [comment]
Resolved by specifying gs:// dataset URL
