### ISSUE TITLE
Minimize insets

### ISSUE THREAD

**Issue by chsher** [klarman-cell-observatory/cirrocumulus#14]
Thank you for creating this great tool! I wanted to suggest an enhancement - when one types in a gene, the heatmap+embedding is shown as an inset at the bottom of the screen, which often obscures the original big embedding. Could you make the insets minimizable, the same way that desktop windows are minimizable, so that they don't overlap with the original big embedding?

**Comment by joshua-gould** [comment]
Thanks for the feedback. Can you please include a screenshot that illustrates the issue? Thanks.

**Comment by chsher** [comment]
Thanks, here is a screenshot. In other words, I'd like to see the original big embedding without having to zoom out, but the gallery takes up more than a third of the screen.
![image](https://user-images.githubusercontent.com/23045343/109426102-b22aeb80-79b9-11eb-8119-33e4aa29fdb5.png)

**Comment by joshua-gould** [comment]
Do you want the primary embedding to take up the full window height and
users would have to scroll to see the gallery? Thanks.

**Comment by chsher** [comment]
Yes, I would love that!

**Comment by joshua-gould** [comment]
In version 1.1.14.post2, you can drag the divider below the primary embedding chart to resize the view. Please let me know how this works for you. Thanks.

**Comment by chsher** [comment]
Thank you @joshua-gould! I upgraded to 1.1.14.post2 and unfortunately don't see a divider to drag. Here is the version I am currently using and a screenshot of the cirro launch page:
![image](https://user-images.githubusercontent.com/23045343/109733108-7dbb5900-7b8c-11eb-87a4-39761dcb4aa0.png)
![image](https://user-images.githubusercontent.com/23045343/109733152-8f046580-7b8c-11eb-8940-97e01d6eac41.png)

**Comment by joshua-gould** [comment]
Perhaps your browser is caching the webpage? Can you please try clearing your cache and reloading the page? The interface should look like this:
<img width="1219" alt="Screen Shot 2021-03-02 at 8 46 59 PM" src="https://user-images.githubusercontent.com/5237151/109740105-b6612f80-7b98-11eb-9316-fcd0a5f5dc0a.png">

**Comment by chsher** [comment]
Thank you @joshua-gould, it worked! All set!
