### ISSUE TITLE
MongoDB question

### ISSUE THREAD

**Issue by dl016d** [klarman-cell-observatory/cirrocumulus#16]
How to add data into MongoDB?  Can I load data directly into MongoDB or have to use the API to load the data?  any detailed instructions? thanks.

**Comment by joshua-gould** [comment]
You can programmatically add a dataset by posting to the /api/dataset endpoint:
curl http://localhost:5000/api/dataset -X POST -F 'name=my_name' -F 'url=data/my_dataset_path' -F 'description=my_desc'  -F 'species=Mus musculus'

See https://cirrocumulus.readthedocs.io/en/latest/installation.html#server-mode.

**Comment by dl016d** [comment]
Thanks for the reply.  Is there a way to load data not using API but using mongoimport from MongoDB? Thanks.

**Comment by joshua-gould** [comment]
Yes. You can see the document structure in mongo after using the user
interface or API to insert a dataset.
