### ISSUE TITLE
"No matching index found" error when attempting to open a dataset with Google App Engine hosted cirrocumulus

### ISSUE THREAD

**Issue by ianno-s** [klarman-cell-observatory/cirrocumulus#29]
After following the instructions on how to set up a cirrocumulus server on Google App Engine, I am not able to open datasets after adding them via URL. The frequent error message I get is `google.api_core.exceptions.FailedPrecondition: 400 no matching index found`. Is there some configuration (adding an index) to the gcloud app that must be done? Or is there some other issue? Thanks!

**Comment by joshua-gould** [comment]
Dataset URLs need to be gs URLs and not http URLs.
